USE [master]
GO

/****** Object:  Database [Students]    Script Date: 7/22/2021 2:17:51 PM ******/
CREATE DATABASE [Students]
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [Students] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Students] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Students] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Students] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Students] SET ARITHABORT OFF 
GO

ALTER DATABASE [Students] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Students] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Students] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Students] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Students] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Students] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Students] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Students] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Students] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Students] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Students] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Students] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Students] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Students] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Students] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Students] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Students] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Students] SET RECOVERY FULL 
GO

ALTER DATABASE [Students] SET  MULTI_USER 
GO

ALTER DATABASE [Students] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Students] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Students] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Students] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Students] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Students] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Students] SET  READ_WRITE 
GO

USE [Students]
GO

CREATE TABLE [dbo].[Student](
	[StudentId] [INT] IDENTITY(1,1) NOT NULL,
	[Firstname] [NVARCHAR](50) NOT NULL,
	[Lastname] [NVARCHAR](50) NOT NULL,
 CONSTRAINT [PK_Studenta] PRIMARY KEY CLUSTERED 
(
	[StudentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


INSERT INTO [dbo].[Student]
VALUES
(N'Francesco', N'Basco' ), 
(N'Antonio', N'Rossi' ), 
(N'Mario', N'Verdi' ), 
(N'Fabio', N'Giallo' ), 
(N'Johnny', N'Blue' )